# Generated by Django 5.0.1 on 2024-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
