# Generated by Django 5.0.1 on 2024-02-05 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_good_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
