# Generated by Django 5.0.1 on 2024-02-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_category_good_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='color',
            field=models.CharField(choices=[('Красное', 'red'), ('Белое', 'white')], default='red', max_length=255, verbose_name='Цвет'),
        ),
    ]
