# Generated by Django 5.0.1 on 2024-02-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_good_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='color',
            field=models.CharField(choices=[('red', 'Красное'), ('white', 'Белое')], default='red', max_length=255, verbose_name='Цвет'),
        ),
    ]
