# Generated by Django 5.0.1 on 2024-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
